services:
  mongodb:
    container_name: 'database-vue-express'
    image: 'mongodb/mongodb-community-server'
    restart: 'always'
    volumes:
      - 'mongodb:/var/lib/mongodb/data'
    expose:
      - '27017'
    ports:
      - '27017:27017'
    

volumes:
  mongodb: